[project]
name = "afu"
version = "0.1.0"
description = "AFU - RL Library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["torch", "bbrl"]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["afu"]
